### ISSUE TITLE
Worker thread is not stopped when Unreliables.retryUntilSuccess times out

### ISSUE THREAD

**Issue by greenbird-chr** [rnorth/duct-tape#6]
Unreliables.retryUntilSuccess is currently implemented so that the worker thread never stops calling the lambda if the future times out. 

PR: https://github.com/rnorth/duct-tape/pull/5

**Comment by rnorth** [comment]
Released #5 as duct-tape 1.0.8.

Thank you for the contribution @greenbird-chr, and apologies again for the delay.
